//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControlToioInterfaces
{
    [Serializable]
    public class ToioControlMsg : Message
    {
        public const string k_RosMessageName = "control_toio_interfaces/ToioControl";
        public override string RosMessageName => k_RosMessageName;

        public int left;
        public int right;

        public ToioControlMsg()
        {
            this.left = 0;
            this.right = 0;
        }

        public ToioControlMsg(int left, int right)
        {
            this.left = left;
            this.right = right;
        }

        public static ToioControlMsg Deserialize(MessageDeserializer deserializer) => new ToioControlMsg(deserializer);

        private ToioControlMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.left);
            deserializer.Read(out this.right);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.left);
            serializer.Write(this.right);
        }

        public override string ToString()
        {
            return "ToioControlMsg: " +
            "\nleft: " + left.ToString() +
            "\nright: " + right.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
